### ISSUE TITLE
Implement crud operations for brands

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#21]
**Objective:**
Implement the CRUD operations for the Brand component in the product module.

**Tasks:**
- [x] Create Brand model and migration
- [x] Implement Brand controller, validation, policy and routes
- [x] Create Brand observer and factory
- [x] Add Brand permissions in PermissionSeeder
- [x] Write unit tests for Brand endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
