### ISSUE TITLE
Implement crud operations for category

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#25]
**Objective:**
Implement the CRUD operations for the category component in the product module.

**Tasks:**
- [x] Create category model and migration
- [x] Implement category controller, validation, policy and routes
- [x] Create category observer and factory
- [x] Add category permissions in PermissionSeeder
- [x] Write unit tests for category endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
