### ISSUE TITLE
Implement crud operations for attribute values

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#26]
**Objective:**
Implement the CRUD operations for the attribute values component in the product module.

**Tasks:**
- [x] Create attribute values model and migration
- [x] Implement attribute values controller, validation, policy and routes
- [x] Create attribute values observer and factory
- [x] Add attribute values permissions in PermissionSeeder
- [x] Write unit tests for attribute values endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
