### ISSUE TITLE
Implement crud operations for attributes

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#27]
**Objective:**
Implement the CRUD operations for the attributes component in the product module.

**Tasks:**
- [x] Create attributes model and migration
- [x] Implement attributes controller, validation, policy and routes
- [x] Create attributes observer and factory
- [x] Add attributes permissions in PermissionSeeder
- [x] Write unit tests for attributes endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
