### ISSUE TITLE
Implement crud operations for unit types

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#28]
**Objective:**
Implement the CRUD operations for the unit types component in the product module.

**Tasks:**
- [x] Create unit types model and migration
- [x] Implement unit types controller, validation, policy and routes
- [x] Create unit types observer and factory
- [x] Add unit types permissions in PermissionSeeder
- [x] Write unit tests for unit types endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
