### ISSUE TITLE
Implement crud operations for products

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#29]
**Objective:**
Implement the CRUD operations for the products component in the product module.

**Tasks:**
- [x] Create products model and migration
- [x] Implement products controller, validation, policy and routes
- [x] Create products observer and factory
- [x] Add products permissions in PermissionSeeder
- [x] Write unit tests for products endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
