### ISSUE TITLE
Implement crud operations for adjustment

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#30]
**Objective:**
Implement the CRUD operations for the adjustment component in the product module.

**Tasks:**
- [x] Create adjustment model and migration
- [x] Implement adjustment controller, validation, policy and routes
- [x] Create adjustment observer and factory
- [x] Add adjustment permissions in PermissionSeeder
- [x] Write unit tests for adjustment endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
