### ISSUE TITLE
Implement crud operations for warehouse

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#37]
**Objective:**
Implement the CRUD operations for the warehouse component in the product module.

**Tasks:**
- [x] Create warehouse model and migration
- [x] Implement warehouse controller, validation, policy and routes
- [x] Create warehouse observer and factory
- [x] Add warehouse permissions in PermissionSeeder
- [x] Write unit tests for warehouse endpoints
- [ ] Update API documentation

**Related to Milestone:** Product Module Completion
