### ISSUE TITLE
Implement crud operations for supplier

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#41]
**Objective:**
Implement the CRUD operations for the supplier component in the product module.

**Tasks:**
- [x] Create supplier model and migration
- [x] Implement supplier controller, validation, policy and routes
- [x] Create supplier observer and factory
- [x] Add supplier permissions in PermissionSeeder
- [x] Write unit tests for supplier endpoints
- [ ] Update API documentation

**Related to Milestone:** Purchase Module Completion
