### ISSUE TITLE
Implement crud operations for purchase

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#42]
**Objective:**
Implement the CRUD operations for the purchase component in the product module.

**Tasks:**
- [ ] Create purchase model and migration
- [ ] Implement purchase controller, validation, policy and routes
- [ ] Create purchase observer and factory
- [ ] Add purchase permissions in PermissionSeeder
- [ ] Write unit tests for purchase endpoints
- [ ] Update API documentation

**Related to Milestone:** Purchase Module Completion
