### ISSUE TITLE
Implement crud operations for Purchase Return

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#43]
**Objective:**
Implement the CRUD operations for the purchase return component in the product module.

**Tasks:**
- [ ] Create purchase return model and migration
- [ ] Implement purchase return controller, validation, policy and routes
- [ ] Create purchase return observer and factory
- [ ] Add purchase return permissions in PermissionSeeder
- [ ] Write unit tests for purchase return endpoints
- [ ] Update API documentation

**Related to Milestone:** Purchase Module Completion
