### ISSUE TITLE
Implement crud operations for Payment

### ISSUE THREAD

**Issue by phi-rakib** [phi-rakib/inventory-management-system-api#44]
**Objective:**
Implement the CRUD operations for the payment component in the product module.

**Tasks:**
- [ ] Create payment model and migration
- [ ] Implement payment controller, validation, policy and routes
- [ ] Create payment observer and factory
- [ ] Add payment permissions in PermissionSeeder
- [ ] Write unit tests for payment endpoints
- [ ] Update API documentation

**Related to Milestone:** Purchase Module Completion
